### ISSUE TITLE
Sending Get Request With Proxy Mode Enabled Still Causes Token Invalidation Error

### ISSUE THREAD

**Issue by jn1m** [J3ldo/UGC-Sniper#104]
I learned recently that it was a new security feature implemented by Roblox, that when a Get Request is sent from another IPv4 Address, or proxy, the cookie/authorization token changes. Thus causing an error to occur which is token invalidation. I don't know if there are any bypasses to this or even if it would work on the premium version. But it seems proxy mode has no use anymore. Which in return also makes snipers almost useless as sending so many requests at the same time on the same IP would cause a rate-limit very very fast. Is there a fix to this?

**Comment by jn1m** [comment]
i just realized it might be an issue on my end, but i dont understand why it would be caused.

**Comment by maxhithere** [comment]
your proxy has to be in the same region as your authenticated cookie
