### ISSUE TITLE
crashing when try to bought limits

### ISSUE THREAD

**Issue by opspsp** [J3ldo/UGC-Sniper#112]
![crash1](https://github.com/J3ldo/UGC-Sniper/assets/140855275/0872601f-1a73-47f8-9545-5bfe4b2e34e9)
![image1](https://github.com/J3ldo/UGC-Sniper/assets/140855275/0124d949-d429-4465-880e-fec53d0bd812)

screenshots taken from 2 different computers

**Comment by J3ldo** [comment]
it has a captcha now, give us some time to fix it.
