### ISSUE TITLE
installing requests problem

### ISSUE THREAD

**Issue by awesomeboxlord** [J3ldo/UGC-Sniper#12]
probably very dumb mistake but with python enabled in app extension aliases i get
"Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases"
and with it disabled i get
"'Python' is not recognized as an internal or external command, operable program or batch file"

**Comment by maxhithere** [comment]
https://www.python.org/downloads/

**Comment by mythiclyt** [comment]
Or download Microsoft store version of python 3.10
