### ISSUE TITLE
Error while running program

### ISSUE THREAD

**Issue by mythiclyt** [J3ldo/UGC-Sniper#14]
I have done everything but when I run the main file nothing happens. Do I have to have something opened whole running the code? I have one limited id in the limiteds.txt and my full cookie _|warning.....j38384njo3..... .egg in the cookie.txt. if you need to see picture lmk on ForeverMyth#0508 discord. Please help or show a video how to setup properly

**Comment by mythiclyt** [comment]
How do I run the code ? Do I double click main file or How?

**Comment by jackercrackr** [comment]
1. open command prompt with administrator
2. write `cd: "the location of your main python file (example: C:\Users\username\Downloads\UGC-Sniper-main)"` must include quotation marks
3. write `python main.py`

**Comment by mythiclyt** [comment]
> 

It keeps saying this
![Uploading 20230410_121557.jpg…]()

**Comment by mythiclyt** [comment]
![20230410_121557](https://user-images.githubusercontent.com/130336484/230891606-fa4a5f18-d3a9-4c26-a1fa-b8c757df89ac.jpg)
It keeps saying this

**Comment by wsley22** [comment]
i have the same issue

**Comment by mythiclyt** [comment]
> i have the same issue

I found out how. Don't include quotation marks or colon e.g cd C:User..........

**Comment by jackercrackr** [comment]
> I found out how. Don't include quotation marks or colon e.g cd C:User..........
yeah, my bad.

**Comment by jackercrackr** [comment]
> I found out how. Don't include quotation marks or colon e.g cd C:User..........

yeah, my bad..

**Comment by afyy01** [comment]
im on mac and it says permission denied

**Comment by JFitzyz** [comment]
Opening the script itself didn't work for me, but running it though my directory on CMD prompt did. Thanks jackercrackr!
