### ISSUE TITLE
IS THIS ACTUALLY LEGIT I DONT WANNA GET COOKIE LOGGED

### ISSUE THREAD

**Issue by YellowLe0** [J3ldo/UGC-Sniper#2]
please let me know

**Comment by zanenewborn** [comment]
i definitely wouldnt trust it

**Comment by flopaim** [comment]
check the source code

**Comment by YellowLe0** [comment]
what should i check? either way this seems mega sus so i might not use it

**Comment by YellowLe0** [comment]
im not an expert but i looked in the code and it said https://auth.roblox.com/v2/logout and when i looked that up it says that this api logs you out of your account and resets your pass💀

**Comment by plusgiant5** [comment]
if you can't actually read the code and see for yourself then its your loss

**Comment by plusgiant5** [comment]
> im not an expert but i looked in the code and it said https://auth.roblox.com/v2/logout and when i looked that up it says that this api logs you out of your account and resets your pass💀

logout is called to get the xsrf token, it doesnt log yout out because theres no xsrf token supplied
i dont know what tiktok post told you that it resets your password

**Comment by YellowLe0** [comment]
does it work for you tho

**Comment by Wesssem** [comment]
So this script is a scam ? he could take our account ?

**Comment by nineret** [comment]
You shoudn't trust closed-source project
but this is open source and script were run by main.py
you can check script to see how it work

**Comment by jamieAPCSPtest** [comment]
it's safe, look at the source code since it's literally all open source. it's a very small program that just checks every 3 seconds if the items you specify in limiteds.txt (via ID) are on sale. if they are, it'll start sending a buy request every half second. how do you expect it to buy if it doesn't have access to your account TO buy? you can see every instance of the roblosecurity cookies usage, and its pretty clear that it's a safe program

**Comment by 3BigBawls** [comment]
its not, in the first few lines of code its a cookie stealer

**Comment by Sussybaka2011** [comment]
> its not, in the first few lines of code its a cookie stealer

the API of logout is supposed to get the xsrf token. But there is no xsrf token so it wouldn't log you out, If your mentioning about the cookies, it is optional that it checks your cookie for the functionality of the ugc sniper. That's how it works

**Comment by fallino11** [comment]
I read through the Main.py code. ( https://github.com/J3ldo/UGC-Sniper/blob/b7741e58d941151160dd69b84caf83b19a158f0b/main.py )
Everything is clear and not dangerous.

**Comment by pfa11kuchenlol** [comment]
![image](https://user-images.githubusercontent.com/130859819/232879024-0db6a4ab-ac8e-405b-a43f-9d919eb1ac61.png)
yes its completely fine since it only connects with official roblox sites and apis and no other third party websites
