### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Bavly-Awad** [J3ldo/UGC-Sniper#21]
Hey man, im getting an erorr on the requests.

**Comment by dobrin-glitch** [comment]
u have to download the request libary

**Comment by Bavly-Awad** [comment]
I did, then I get an error. When I run it in VSCODE. 
![image](https://user-images.githubusercontent.com/67879620/231184068-2321a36b-afee-408c-9833-b8961d77d8e3.png)

**Comment by Zelvak06** [comment]
I have problem when i trying add the files to the extensions of google chrome it says error couldnt read the thingy 
can saomeone help me pls
