### ISSUE TITLE
Replit

### ISSUE THREAD

**Issue by MeekTortoise** [J3ldo/UGC-Sniper#24]
Can i run this on replit?

**Comment by sb122** [comment]
you could but its a bad idea because projects on replit are public which means people can see your roblosecurity cookie

**Comment by afyy01** [comment]
How can you do it on repl?

**Comment by realpritam** [comment]
How to bypass ip lock it replit?

**Comment by realpritam** [comment]
And i have replit pro

**Comment by J3ldo** [comment]
You cant run this on replit roblox blocks those ips

**Comment by realpritam** [comment]
> You cant run this on replit roblox blocks those ips

AWS or azure?

**Comment by J3ldo** [comment]
Aws you can
