### ISSUE TITLE
i cant fix this

### ISSUE THREAD

**Issue by dobrin-glitch** [J3ldo/UGC-Sniper#25]
![grafik](https://user-images.githubusercontent.com/130359952/230965818-6151dc7a-db3d-4859-ba4d-ad66361df653.png)
this is what i get now

![230915454-7bd56bf0-69f5-4913-8b6c-bf49f479d6dd](https://user-images.githubusercontent.com/130359952/230965846-7d09e643-8f35-4aeb-8d06-73b9c9bdb043.png)
and this is what i got before i deleted the code that was there

How can i fix this ??

**Comment by murderee** [comment]
> > ![grafik](https://user-images.githubusercontent.com/130359952/230965818-6151dc7a-db3d-4859-ba4d-ad66361df653.png) this is what i get now
> > ![230915454-7bd56bf0-69f5-4913-8b6c-bf49f479d6dd](https://user-images.githubusercontent.com/130359952/230965846-7d09e643-8f35-4aeb-8d06-73b9c9bdb043.png) and this is what i got before i deleted the code that was there
> > How can i fix this ??
> 
> and i have the file limiteds [limiteds.txt](https://github.com/J3ldo/UGC-Sniper/files/11192827/limiteds.txt)

For me, this is how I fixed it on windows

For mac,
In main.py in the sniper folder IDLE code, I edited the line where it says

`with open("limiteds.txt", "r") as f:
limiteds = f.read().replace(" ", "").split(",")

with open("cookie.txt", "r") as f:
cookie = f.read()`

Where I changed "cookie.txt" with /Users/[username]/Downloads [where folder is]/UGC-Sniper-main/cookie.txt
and "limiteds.txt" with /Users/[username]/Downloads [where folder is]/UGC-Sniper-main/limited.txt

-- for windows, repeat the same steps but change path names to C:\Users\[username]\Documents[where folder is]\UGC-Sniper-main\cookie/limited.txt [text file name]

I only know how to get full path names for mac, not windows, so windows might not work. I only tried this once with a friends computer that uses windows 10.

**Comment by afyy01** [comment]
Hey can someone give me a guide on how to do this on mac?
my discord is aba#8741

**Comment by murderee** [comment]
> For mac, In main.py in the sniper folder IDLE code, I edited the line where it says
> 
> `with open("limiteds.txt", "r") as f: limiteds = f.read().replace(" ", "").split(",")
> 
> with open("cookie.txt", "r") as f: cookie = f.read()`
> 
> Where I changed "cookie.txt" with /Users/[username]/Downloads [where folder is]/UGC-Sniper-main/cookie.txt and "limiteds.txt" with /Users/[username]/Downloads [where folder is]/UGC-Sniper-main/limited.txt



> Hey can someone give me a guide on how to do this on mac? my discord is aba#8741

do you need help fixing it or installing it?

**Comment by afyy01** [comment]
Both really because the installing request part does not  work for me so i could really use a full on guide
Thank you!

**Comment by murderee** [comment]
> Both really because the installing request part does not work for me so i could really use a full on guide Thank you!

an easy fix for installing request is just to run `pip3 install requests`

**Comment by afyy01** [comment]
It worked thank you, would you know the next step, sorry and thank you again

**Comment by afyy01** [comment]
I have my cookie into the cookie.txt and after that what do i do?

**Comment by afyy01** [comment]
I have done everything but how do i start it? does it just automatically start when i open it?
