### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Tenzo777** [J3ldo/UGC-Sniper#3]
what do i need to put in limited text, the ugc name or id or link

**Comment by YellowLe0** [comment]
Dont use it

**Comment by novice-invoice** [comment]
The ID.

**Comment by Wesssem** [comment]
Traceback (most recent call last):
  File "C:\Users\Megaport\Downloads\UGC-Sniper-main\main.py", line 106, in <module>
    json={"itemIds": [info["collectibleItemId"]]},
KeyError: 'collectibleItemId'

**Comment by Wesssem** [comment]
how to fix this error ?
