### ISSUE TITLE
Error After Running the main.py file.

### ISSUE THREAD

**Issue by jKod1** [J3ldo/UGC-Sniper#33]
Hi, i just runned the code and i got the next error
`Traceback (most recent call last):
  File "C:\Users\PC\Desktop\UGC-Sniper-main\main.py", line 1, in <module>
    import requests as r
ModuleNotFoundError: No module named 'requests'`

Does this mean that the script beggining is failing to start looking for the limited because is set to anything?

**Comment by popcrocks** [comment]
no it means u are a retard

**Comment by jKod1** [comment]
Oh wow discarding your way of answering my question, so what is the reason why I receive that message?

**Comment by fallino11** [comment]
Read the Readme.md ( https://github.com/J3ldo/UGC-Sniper/blob/main/README.md )
You need to install the "requests" library.
Here is an advanced guide: https://www.geeksforgeeks.org/how-to-install-requests-in-python-for-windows-linux-mac/

**Comment by jKod1** [comment]
> Read the Readme.md ( https://github.com/J3ldo/UGC-Sniper/blob/main/README.md ) You need to install the "requests" library. Here is an advanced guide: https://www.geeksforgeeks.org/how-to-install-requests-in-python-for-windows-linux-mac/

Thank you for your responding, sorry about my mistake, i did read that part, solved it.
