### ISSUE TITLE
Problem while running script

### ISSUE THREAD

**Issue by labcat69** [J3ldo/UGC-Sniper#36]
idk what this is 
![image](https://user-images.githubusercontent.com/130503585/231269230-5047fff9-81be-4650-a415-8eac4c924670.jpg)

**Comment by jKod1** [comment]
You probably wrote wrong your cookiesecurity try try to enter it correctly in "cookies" file.

**Comment by jKod1** [comment]
Uhm in this case the error comes from the ugc limited id, did you write the number correctly?

**Comment by labcat69** [comment]
> Uhm in this case the error comes from the ugc limited id, did you write the number correctly?

Doni have to paste the link or the id only?

**Comment by gumblehige** [comment]
How do i get that bot??
