### ISSUE TITLE
problem while running script

### ISSUE THREAD

**Issue by kitekziomal2** [J3ldo/UGC-Sniper#38]
hello, i runned the script and got this error

![image](https://user-images.githubusercontent.com/130503978/231275526-39ff3026-b513-4437-b3cd-f6b81c4d96e5.png)

**Comment by jKod1** [comment]
You have to set only the ID (number) of the item.

**Comment by kitekziomal2** [comment]
i put the id only and it doesnt work


![image](https://user-images.githubusercontent.com/130503978/231276980-be725e03-8646-43dd-96af-0b2eed6673e0.png)

**Comment by jKod1** [comment]
delete de comma, you only have to write it when you are going for more than 2 items

**Comment by kitekziomal2** [comment]
now it works, thank you so much!
