### ISSUE TITLE
How to run main.py?

### ISSUE THREAD

**Issue by afyy01** [J3ldo/UGC-Sniper#41]
I have done everything all I have to do is run main.py
So how do I run main.py also I’m on mac

**Comment by Testing9067** [comment]
You dumb retarded fuck,
Download python then python3 or python main.py, it really ain't hard

**Comment by afyy01** [comment]
> You dumb retarded fuck,
> Download python then python3 or python main.py, it really ain't hard

I’m sorry but but like what am I supposed to do when this happens?
![8024C45A-A824-4AC7-A11D-46085075A426](https://user-images.githubusercontent.com/103791068/231322722-2bbd02a2-5adf-4b78-9bc5-77cee67632b6.jpeg)
