### ISSUE TITLE
how to do step 1

### ISSUE THREAD

**Issue by sansan3d** [J3ldo/UGC-Sniper#43]
when i write pip install requests or python -m pip install requests on python, it says SyntaxError: invalid syntax

**Comment by fallino11** [comment]
You have to use the "Command Prompt" to do it.
More information here: https://www.geeksforgeeks.org/how-to-install-requests-in-python-for-windows-linux-mac/

**Comment by sansan3d** [comment]
when i typed it, it shows nothing. does it mean work?

**Comment by Themaiamiguy2** [comment]
> You have to use the "Command Prompt" to do it. Press WIN + R and enter "cmd.exe". More information here: https://www.geeksforgeeks.org/how-to-install-requests-in-python-for-windows-linux-mac/

Nah it's a scam it just show me: "python -m pip install requests
'C:\Users\User' is not recognized as an internal or external command,
operable program or batch file.
