### ISSUE TITLE
problem while running script

### ISSUE THREAD

**Issue by niznauk** [J3ldo/UGC-Sniper#44]
![Script_Problem](https://user-images.githubusercontent.com/130575165/231481215-c9e8468c-3790-4aae-b266-840fde7de5c8.PNG)
problem while running script

**Comment by fallino11** [comment]
Read the Readme.md ( https://github.com/J3ldo/UGC-Sniper/blob/main/README.md )
You need to install the "requests" library.
Here is an advanced guide: https://www.geeksforgeeks.org/how-to-install-requests-in-python-for-windows-linux-mac/

**Comment by niznauk** [comment]
> Read the Readme.md ( https://github.com/J3ldo/UGC-Sniper/blob/main/README.md ) You need to install the "requests" library. Here is an advanced guide: https://www.geeksforgeeks.org/how-to-install-requests-in-python-for-windows-linux-mac/

TYSM!! it works
