### ISSUE TITLE
problem when running main.py

### ISSUE THREAD

**Issue by namiiman** [J3ldo/UGC-Sniper#49]
Whenever I open the file it just crashes immediately. Is there any way I could fix this?

**Comment by fallino11** [comment]
Check #33

**Comment by namiiman** [comment]
I already installed the requests library. Are there any other reasons as to why this is happening

**Comment by fallino11** [comment]
I need more information to find out, what is wrong.
Could you try to open it with IDLE?

**Comment by ticktockbyjoji** [comment]
> I already installed the requests library. Are there any other reasons as to why this is happening

Try putting the
ID of the limiteds you want, if you do 3 it's best preferred.
The limited item's ID's should be like:
ID, ID, ID
You should also put your cookie in "cookie.txt" when you put it in make sure it doesnt have any spaces. Also make sure to only press "copy to clipboard" if you're using roblofetcher. Not "copy full token to clipboard".
