### ISSUE TITLE
starting the main python file

### ISSUE THREAD

**Issue by averagedogmassager** [J3ldo/UGC-Sniper#50]
when i start the file named "main" it crashes almost instantly, and idk what to do with proxies

**Comment by averagedogmassager** [comment]
![image](https://user-images.githubusercontent.com/130595478/231543331-cd8cd59c-d5b6-49a5-bb48-e5892636d8d2.png)
i have this error

**Comment by fallino11** [comment]
Check #33

**Comment by Vcsk** [comment]
> dumbass run `python3 -m pip install requests` or `pip install requests` in terminal

nah it says "invalid syntax"
