### ISSUE TITLE
Syntax error and crashing

### ISSUE THREAD

**Issue by ToxicTrooper197** [J3ldo/UGC-Sniper#59]
So when I try to open the file with python it crashes immediately, but when I open python then just paste the code in there this happens:![image](https://user-images.githubusercontent.com/121409790/231944895-98b5cc66-d3aa-497a-8332-930c15fb36b9.jpeg) IM using python 3.11

**Comment by ToxicTrooper197** [comment]
I FIXED IT WW

**Comment by pfa11kuchenlol** [comment]
> I FIXED IT WW

how
