### ISSUE TITLE
ValueError: Invalid header value b' (FIXED)

### ISSUE THREAD

**Issue by murderee** [J3ldo/UGC-Sniper#6]
Don't know if this has something to do with me being on macos, but when executed I receive the error: `ValueError: Invalid header value b'.[roblox cookie]\n'`

**Comment by murderee** [comment]
just tried on windows replacing `cookie.txt` and `limiteds.txt` with full path name, and it worked, but doing the same on macos didn't.

**Comment by wsley22** [comment]
i have this issue on windows

**Comment by mythiclyt** [comment]
> just tried on windows replacing `cookie.txt` and `limiteds.txt` with full path name, and it worked, but doing the same on macos didn't.
Can you explain more? I need help.

**Comment by murderee** [comment]
> 
For mac,
In `main.py` in the sniper folder IDLE code, I edited the line where it says 

`with open("limiteds.txt", "r") as f:
    limiteds = f.read().replace(" ", "").split(",")

with open("cookie.txt", "r") as f:
    cookie = f.read()`

Where I changed "cookie.txt"  with `/Users/[username]/Downloads [where folder is]/UGC-Sniper-main/cookie.txt`
and "limiteds.txt" with `/Users/[username]/Downloads [where folder is]/UGC-Sniper-main/limited.txt`


-- for windows, repeat the same steps but change path names to `C:\Users\[username]\Documents[where folder is]\UGC-Sniper-main\cookie/limited.txt [text file name]`

**Comment by murderee** [comment]
im so dumb I just realised it didn't work bc I had an extra space after my cookie ;-;
