### ISSUE TITLE
Problem with running

### ISSUE THREAD

**Issue by rgeg34g43** [J3ldo/UGC-Sniper#64]
![Снимок экрана 2023-04-15 005943](https://user-images.githubusercontent.com/130801098/232162048-e7c933a8-fe2d-4250-a35a-b2b8607d9614.png)
wth

**Comment by StateLeon** [comment]
You need to install the requests library, do so by going into cmd and running "pip install requests" or with python 3 "pip3 install requests"

**Comment by rgeg34g43** [comment]
thx its work
