### ISSUE TITLE
it said "Invalid syntax"

### ISSUE THREAD

**Issue by mecoems** [J3ldo/UGC-Sniper#66]
idk what I'm doing wrong 
![Screenshot 2023-04-15 081320](https://user-images.githubusercontent.com/130808419/232176005-63114f03-30ed-49f8-a76c-af8cf9780bfb.png)

**Comment by mecoems** [comment]
I see people saying that I have to use command promt, but it doesn't work either 
![image](https://user-images.githubusercontent.com/130808419/232176286-6b9803dc-6f88-4ce9-a375-4fc79a04b40e.png)

**Comment by StateLeon** [comment]
Try running the command "where python" this will check if you firstly have python installed. If it displays a python.exe location then you have it installed but make sure to check what version it is running. Preferably Python 3.11. After you run all the checks and update it you need then try just running "pip3 install requests" in cmd.

**Comment by fallino11** [comment]
Use `py -m pip install requests` instead of `python -m pip install requests`
Use that in command prompt. (see the screenshot.)
![image](https://user-images.githubusercontent.com/81523464/232210344-321723df-a7ca-4e25-b41d-c38e29c81b24.png)
