### ISSUE TITLE
main.py closing instantly

### ISSUE THREAD

**Issue by kidbengalahehe** [J3ldo/UGC-Sniper#69]
Guys, I can't use the bot, because when I open main.py, python opens and closes instantly, and I already installed the request library, could someone tell me what's going on?

**Comment by TheGamingCave** [comment]
ok, I had the same problem and it was because my cookie had a space at the very end, if you remove it it will fix the problem, at least that's what I did and it fixed it!

**Comment by kidbengalahehe** [comment]
did not work
