### ISSUE TITLE
.

### ISSUE THREAD

**Issue by OmarAmgad8357** [J3ldo/UGC-Sniper#70]
.

**Comment by burnlosper** [comment]
Let me break the code down for you as you clearly cant read the python script. 

This is a Python script that automates the purchase of limited items from the Roblox marketplace.

The script reads two text files: "limiteds.txt" and "cookie.txt". "limiteds.txt" contains a list of the limited items that the script should attempt to purchase, while "cookie.txt" contains the user's authentication cookie for Roblox.

The script then uses the Roblox API to obtain the authenticated user's ID, and starts a separate thread to periodically obtain an X-CSRF-Token required for making requests to the Roblox API.

The main loop of the script repeatedly queries the Roblox API for details about each item in the "limiteds.txt" file. If an item is available for purchase, the script attempts to buy it using the purchasedetails endpoint. If the purchase is successful, the script prints a message indicating success. If the purchase is unsuccessful, the script tries again until the item is sold out or a limit is reached.

The script uses time.sleep() to implement a cooldown period between purchase attempts. The length of the cooldown period is calculated based on the number of items in the "limiteds.txt" file. The script also prints a message indicating how long the script took to execute and how long it should ideally take, as well as how many items were successfully purchased during the current execution.

Now with all of this considered.

**Comment by burnlosper** [comment]
No, this code does not send your Roblox API to another user. The code retrieves your own user ID by sending a request to the Roblox API using the authentication cookie you provide in cookie.txt. It then uses this user ID to purchase limited items on your account. The code does not send any information about your API or authentication cookie to another user.

**Comment by OmarAmgad8357** [comment]
yea yea, I wanted to close it, bc it was a wrong project

**Comment by OmarAmgad8357** [comment]
thats why I edited it it had a similar name to urs anyways thanks
