### ISSUE TITLE
how to do Step 4?

### ISSUE THREAD

**Issue by xcvair** [J3ldo/UGC-Sniper#71]
i dont understand

**Comment by ZZV-4** [comment]
Asset1, Asset2, Asset3 | Thats an example of what you put in. The ids of the ugc limiteds.

**Comment by ZZV-4** [comment]
you can find the id in the link of the limited

**Comment by xcvair** [comment]
> you can find the id in the link of the limited
SO i need id and asset like this? 14189294819 - Asset1

**Comment by ZZV-4** [comment]
> 

Yes
