### ISSUE TITLE
alguem br q saiba me explicar como resolve essa bosta ?

### ISSUE THREAD

**Issue by Rafaoss1204330** [J3ldo/UGC-Sniper#77]
![image](https://user-images.githubusercontent.com/131078940/232659140-e8096daf-4d94-4dfa-a481-f0e8f549277c.png)

**Comment by Rafaoss1204330** [comment]
> Você tem que baixar o python e o pip. Depois você tem que executar o arquivo via cdm. No caso quando você estiver dentro do endereço pelo cmd é só dar o comando de execução: "python main.py"

**Comment by Rafaoss1204330** [comment]
> Você tem que baixar o python e o pip. Depois você tem que executar o arquivo via cdm. No caso quando você estiver dentro do endereço pelo cmd é só dar o comando de execução: "python main.py"

eu nao entendi como assim via cmd? e com o assim dentro do endereço pelo cmd ?

**Comment by EoBerrr** [comment]
- Primeiro abre o cmd
![brave_XGKspf8xOq](https://user-images.githubusercontent.com/86076081/233519985-cada0752-80aa-4d48-9a52-7c6b639ced54.png) 
- Depois copie o endereço de onde o sniper-bot está
![explorer_fKgJonn8lE](https://user-images.githubusercontent.com/86076081/233520290-dd34b908-7aa1-4d60-ab26-f2bf5945d564.png)
- Depois disso cole no cmd 
  obs.: 
  Tem que colocar o "cd" na frente
  Se você tiver mais de uma repartição e o bot estiver em uma repartição diferente da do Sistema Operacional você vai ter que colocar o "nome da repartição" + ":" exemplo: "g:". Depois aperta enter e faça o passo de cima
![cmd_yFmC0IDVO5](https://user-images.githubusercontent.com/86076081/233520466-35d833d8-ff86-4807-bf68-c00653a670c4.png)
- O resultado final vai ser mais ou menos assim
![cmd_qPW6mCYfSv](https://user-images.githubusercontent.com/86076081/233521068-ba8f9f89-e63f-444e-8fa3-9fa6cc224745.png)

Após isso é só dar o comando: "python main.py"
Se não reconhecer que o Python esta instalado me fala. É fácil de resolver.
