### ISSUE TITLE
what do i do in requeired json in themes

### ISSUE THREAD

**Issue by afyy01** [J3ldo/UGC-Sniper#87]

**Comment by afyy01** [comment]
<img width="708" alt="Screenshot 2023-04-29 at 11 48 12 a m" src="https://user-images.githubusercontent.com/103791068/235298747-b1827e01-4e7f-4f24-be66-faa1bb216805.png">

**Comment by J3ldo** [comment]
Those are all the variables. For example

printText.txt
``
[COLOR_GREEN]Time [_time][COLOR_WHITE]
``
Variables don't work in logo.txt
