### ISSUE TITLE
KeyError: 'id'

### ISSUE THREAD

**Issue by sillysillych** [J3ldo/UGC-Sniper#9]
When executed get this error:

Traceback (most recent call last):
  File "main.py", line 15, in <module>
    user_id = r.get("https://users.roblox.com/v1/users/authenticated", cookies={".ROBLOSECURITY": cookie}).json()["id"]
KeyError: 'id'

**Comment by maxhithere** [comment]
put a valid roblox cookie

**Comment by murderee** [comment]
> put a valid roblox cookie

I did, but found for windows you need to replace "limiteds.txt" and "cookie.txt" with full path name in the script. 

For mac, same error with a valid cookie.
