### ISSUE TITLE
Speed is 2 times slower than before

### ISSUE THREAD

**Issue by Rogox14** [J3ldo/UGC-Sniper#93]
![image](https://user-images.githubusercontent.com/77737200/236649507-3c756463-518f-4f92-86ff-1491f6a353b3.png)
How can I make speed faster? It was about 1.1 before.

**Comment by NikSavchenk0** [comment]
yea bot is working slow, so use proxy is faster 0.30 seconds.

**Comment by NikSavchenk0** [comment]
yea bot is working slow, is not getting new update(
