### ISSUE TITLE
running program causes roblox cookie to change.

### ISSUE THREAD

**Issue by jn1m** [J3ldo/UGC-Sniper#96]
i dont understand whats happening but whenever i run the program (with the correct cookie) and i actually run the sniper it will give me a token validation error. i go and get my cookie for a second time and its completely different. i tried like 3 times to see what happened and it changed my cookie everytime. i dont know what it could be tbh. someone help? thanks in advanced.

**Comment by maxhithere** [comment]
you aren't pasting your cookie correctly
