### ISSUE TITLE
Don’t work please help

### ISSUE THREAD

**Issue by Maxeye0710** [J3ldo/UGC-Sniper#99]
https://github.com/J3ldo/UGC-Sniper/assets/133915845/d09115d6-1e0d-4c42-955a-1b5bd89891f9

**Comment by Maxeye0710** [comment]
😔

**Comment by DamDasUwU** [comment]
Привет! Я хоть и не разработчик данного скрипта, но могу тебе помочь.

1. Попробуй переустановить Python (Последней версии и снизу поставить галочку "Add..." что-то там, точно не помню что там написано)
2. Зайди в папку с UGC Sniper,
    В строчку пути напиши "cmd.exe", 
    У тебя откроется консоль, 
    Там пиши "python main.py"
  Ну и всё должно работать
  3. Проверь, вставил ли ты токен
  4. Если мои советы не посмотри посмотри туториал (Он в описание на страничке скрипта)
  5. Зайди в папку с UGC Sniper,
    В строчку пути напиши "cmd.exe", 
    У тебя откроется консоль, 
    Там пиши "pip install -r requirements.txt"
  
  А так если захочешь, дай свой Discord ник, я тебе напишу и смогу тебе более точнее сказать в чём у тебя ошибка, просто по одному видео не очень понятно.

**Comment by J3ldo** [comment]
Just run with normal python, not IDLE

**Comment by Maxeye0710** [comment]
> Привет! Я хоть и не разработчик данного скрипта, но могу тебе помочь.
> 
> 1. Попробуй переустановить Python (Последней версии и снизу поставить галочку "Add..." что-то там, точно не помню что там написано)
> 2. Зайди в папку с UGC Sniper,
>    В строчку пути напиши "cmd.exe",
>    У тебя откроется консоль,
>    Там пиши "python main.py"
>    Ну и всё должно работать
> 3. Проверь, вставил ли ты токен
> 4. Если мои советы не посмотри посмотри туториал (Он в описание на страничке скрипта)
> 5. Зайди в папку с UGC Sniper,
>    В строчку пути напиши "cmd.exe",
>    У тебя откроется консоль,
>    Там пиши "pip install -r requirements.txt"
> 
> А так если захочешь, дай свой Discord ник, я тебе напишу и смогу тебе более точнее сказать в чём у тебя ошибка, просто по одному видео не очень понятно.
maxeye#7091

**Comment by Maxeye0710** [comment]
> Just run with normal python, not IDLE

Don’t work
